version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Amadou_dev301030"
      MYSQL_DATABASE: "TestProjetJava"
      MYSQL_USER: "amadou-dev"
      MYSQL_PASSWORD: "Amadou_dev301030"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:v1.13
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH: "amadou-dev:Amadou_dev301030"
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

    volumes:
      - mailpit_data:/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  mysql_data:
  redis_data:
  mailpit_data:
